version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-image:latest
    container_name: charrez-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /app/img/uploads:/app/img/uploads
    ports:
      - 8080:8080
    networks:
      - server-db

  front-end:
    image: next-image:latest
    container_name: charrez-gui
    restart: unless-stopped
    ports:
      - 3000:3000

  db:
    image: mongo:4.0.20-xenial
    container_name: db
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - server-db
    volumes:
      - data_db:/data/db

networks:
  server-db:
    driver: bridge

volumes:
  data_db:
    name: ${VOLUME_DB}
