version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-image/node-web-app:latest
    container_name: charrez-server
    restart: unless-stopped
    environment:
      - MONGO_HOSTNAME=db
      - ENGINE_HOST=http://localhost:8000
    env_file:
      - .env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /app:/app
    ports:
      - 8080:8080
    networks:
      - app-network

  front-end:
    image: next-image/node-web-app:latest
    container_name: charrez-gui
    restart: unless-stopped
    ports:
      - 3000:3000

  db:
    image: mongo:4.0.20-xenial
    container_name: db
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
  node_modules:
